implementato il server networkhandler del peer
xBlue0/AlaKazaam pull request #2
Opened 2018-04-16 15:34 UTC by jhonrambo93

2018-04-16 16:00 UTC, GiovanniFiorini commented on peer/handler/NetworkHandler.py
> +			if pktid == LocalData.get_sent_packet():
Perchè questo controllo? tu stai inoltrando un pacchetto non stai attendendo una riposta a qualcosa che hai inviato

2018-04-16 19:26 UTC, NicFontana requested changes

2018-04-16 19:26 UTC, NicFontana commented on peer/LocalData.py
> +	received_packets = dict()
E' sufficiente salvarsi il pktid, tanto è l'unica cosa che viene controllata

2018-04-16 19:26 UTC, NicFontana commented on peer/handler/NetworkHandler.py
> +			sd.close()
La socket può essere chiusa dopo che abbiamo fatto la getpeername alla riga 58. Non so perché, ma anche io avevo questa versione nel mio NetworkHandler, effettivamente non ha senso chiuderla qua

2018-04-17 13:33 UTC, NicFontana commented on peer/handler/NetworkHandler.py
> +			if pktid == LocalData.get_sent_packet():
Si @GiovanniFiorini ripensandoci, si mette questo controllo per verificare se quello che mi è arrivato da qualcuno è un pacchetto che io ho generato e fatto partire in rete, e quindi mi è arrivato erroneamente.

2018-04-17 13:36 UTC, NicFontana approved these changes

2018-04-17 13:36 UTC, merged