Super peer timed handler
xBlue0/AlaKazaam pull request #3
Opened 2018-04-16 15:51 UTC by GiovanniFiorini

Versione Base del TimedRequestHandler (TRH) per il Superpeer.

Viene chiamato dal MenuHandler (MH) del Superpeer per gestire diversi comportamenti:

1)quando l'utente effettua una ricerca file, il MH lancia nella Superpeer Network una QUER
       --> **TRH attende 20s le varie AQUE e le colleziona in una stuttura dati (peer_files)**
              -->poi il MH deve dare all'utente la possibilità di scaricare

2)quando da un peer arriva una FIND, il MH costruisce una QUER
       -->**TRH  attende 20s le varie AQUE e le colleziona in una stuttura dati (peer_files)**
              -->poi il MH deve dare costruire la AFIN per il peer

3)quando l'utente effettua una ricerca di vicini, il MH lancia nella Superpeer Network una SUPE
       --> **TRH attende 20s le varie ASUP e le colleziona in una stuttura dati (super_friends)
                 e printa una risposta alla volta sul terminale "New Friend Found.."**

2018-04-16 20:11 UTC, NicFontana requested changes

2018-04-16 20:11 UTC, NicFontana commented on superpeer/handler/TimedResponseHandler.py
> +
Io gio questo blocco di codice lo sposterei sopra, precisamente sotto alla ricezione della command. In questo modo lo si scrive solo una volta

2018-04-16 20:11 UTC, NicFontana commented on superpeer/handler/TimedResponseHandler.py
> +
Sennò vedi, ti tocca riscriverlo gombà

2018-04-16 20:11 UTC, NicFontana commented on superpeer/handler/TimedResponseHandler.py
> +			shell.print_red(f"\nInvalid response: {command} -> {wrong_response}\n")
E magari usi questa riga di codice per far vedere cosa è andato storto

2018-04-17 09:03 UTC, GiovanniFiorini commented
@NicFontana Ho spostato quel blocco di codice fuori dagli "if" e per coerenza l'ho spostato anche nel peer TimedResponseHandler

2018-04-17 09:37 UTC, NicFontana approved these changes

2018-04-17 13:45 UTC, marcorambaldi approved these changes

2018-04-17 13:45 UTC, merged