WIP - Implementato ADDF
xBlue0/AlaKazaam pull request #4
Opened 2018-04-16 16:36 UTC by xBlue0

2018-04-16 20:28 UTC, NicFontana requested changes

2018-04-16 20:28 UTC, NicFontana commented on peer/handler/MenuHandler.py
> +				file_md5 = hasher.get_md5(f'shared/{file.name}')
Ti prego dimmi che funziona davvero in stile print con la f 😂

2018-04-16 20:28 UTC, NicFontana commented on peer/LocalData.py
> +	files = list()
@xBlue0 @jhonrambo93 @GiovanniFiorini io voto per ```shared_files```. Siccome abbiamo la ```peer_files```, ```shared_files``` mi sarebbe più chiaro in lettura del codice

2018-04-16 20:28 UTC, NicFontana commented on peer/handler/MenuHandler.py
> +				if 1 < index < len(files):
Non dovrebbe essere 
```python
1 <= index <= len(files)
```
?

2018-04-16 20:28 UTC, NicFontana commented on peer/handler/MenuHandler.py
> +					index = int(index)
Occhio che qua se l'utente ha scelto 1 si sta riferendo al file con indice interno 0, e così via.
O ```index``` lo decrementiamo direttamente qua dopo che l'utente ha scelto, o lo decrementiamo ogni volta nel codice sotto

2018-04-17 09:32 UTC, NicFontana requested changes

2018-04-17 09:32 UTC, NicFontana commented on peer/handler/MenuHandler.py
> +				if 1 <= index <= len(files):
Fede se decrementi index subito, qua va da 0 a len(files)-1

2018-04-17 12:23 UTC, marcorambaldi approved these changes

2018-04-17 21:44 UTC, NicFontana requested changes

2018-04-17 21:44 UTC, NicFontana commented on peer/LocalData.py
> +	def find_shared_file(cls, index: int) -> tuple:
Questa è più una get volendo essere pignoli, giusto? 😂

2018-04-17 21:44 UTC, NicFontana commented on peer/Menu.py
>  		shell_colors.print_blue('\nBye!\n')
Un controllino sulla ALGO che ci si aspetta in risposta?

2018-04-17 21:44 UTC, NicFontana commented on peer/handler/MenuHandler.py
> +				files = LocalData.get_shared_files()
Magari spostiamo questa riga di codice sopra al ciclo for, così non dobbiamo recuperarli due volte (in enumerate e qua)

2018-04-17 21:44 UTC, NicFontana commented on peer/handler/MenuHandler.py
> +				shell.print_red(f'\n{search} not found.\n')
Io informerei che c'è stato un errore di rete, che magari l'utente ritenta la ricerca. Così invece crede che il file non ci sia. La ```sock.settimeout()``` di fatto va messa come statement antecedente la ```socket.recv()```

2018-04-17 21:44 UTC, NicFontana commented on peer/handler/MenuHandler.py
> +				if command != "LOGO":
Occhio che il comando di risposta è ALGO

2018-04-18 13:20 UTC, GiovanniFiorini commented on peer/handler/MenuHandler.py
> +			while True:
questo ciclo while deve includere anche "index = input" altrimenti l'app si blocca in un ciclo infinito nel caso in cui venga inserito un index non valido

2018-04-18 13:24 UTC, GiovanniFiorini commented on peer/handler/MenuHandler.py
> +					continue
inoltre io nella versione Superpeer della ADFF ho messo anche la 'scandir' nel while così uno può aggiungere file alla shared molto più dinamicamente.
Non dico che una è giusta e l'altra è sbagliata ma parliamone perchè il comportamento deve essere uguale

2018-04-19 14:28 UTC, marcorambaldi approved these changes

2018-04-19 14:30 UTC, NicFontana approved these changes

2018-04-19 14:30 UTC, GiovanniFiorini approved these changes

2018-04-19 14:34 UTC, merged