Superpeer menuhandler
xBlue0/AlaKazaam pull request #7
Opened 2018-04-17 16:48 UTC by GiovanniFiorini

SUPE e QUER

2018-04-17 21:20 UTC, NicFontana commented
@GiovanniFiorini fai puntare la PR su ```dev``` che così è un casino 😂

2018-04-18 15:03 UTC, jhonrambo93 commented on superpeer/handler/NetworkHandler.py
> +				t.start()
attenzione che il timer deve essere di 20 secondi per la SUPE

2018-04-18 15:06 UTC, marcorambaldi requested changes
Tutto ok direi! Sistema solo il timer a 20 secondi

2018-04-18 21:51 UTC, NicFontana commented on superpeer/LocalData.py
> +			if re.search(query_name, file[0].lower()):
Facciamo il ```lower()``` in fase di aggiunta all lista? Che dici?

2018-04-18 21:51 UTC, NicFontana commented on superpeer/handler/MenuHandler.py
> +						f' {superfriend_ip4}|{superfriend_ip6} on port {superfriend_port}')
Per me sarebbe più bello se la stampa di ```New superpeer found...``` la facesse il TimedResponseHandler ad ogni ASUP ricevuta come in R00tella..che dite? @GiovanniFiorini @jhonrambo93 @xBlue0

2018-04-18 21:51 UTC, NicFontana commented on superpeer/handler/MenuHandler.py
> +							if not LocalData.exist_peer_files(ip4_peer, ip6_peer, peer.port, file.file_md5, file.file_name):
Potrebbe essere superfluo, partendo dal fatto che ad ogni ricerca la lista dei peer_files deve partire vuota

2018-04-18 21:51 UTC, NicFontana commented on superpeer/handler/MenuHandler.py
> +					shell.print_yellow('\nNo matching results from the DB.\n')
Per come la vedo io, quando l'utente, anche se superpeer, fa una ricerca è meglio se i risultati (e i no matching results) gli vengono dati indipendentemente da quale sia la sorgente di quei dati. Quindi senza distinguere tra dati da DB e dati dalla rete. Poi de gustibus, vince la maggioranza 🐤 
P.S. Il codice si semplificherebbe

2018-04-18 21:51 UTC, NicFontana commented on superpeer/handler/MenuHandler.py
> +			spinner = SpinnerThread('Searching peers (ENTER to continue)', 'Research done!')
Piccolo refuso, in realtà "Searching files"

2018-04-18 21:51 UTC, NicFontana commented on superpeer/handler/NetworkHandler.py
> +				t.start()
Ya, roba mia questa

2018-04-19 15:21 UTC, FIAV1 approved these changes

2018-04-19 15:21 UTC, FIAV1 commented on superpeer/handler/MenuHandler.py
> +					dir_file.clear()
Riga di codice inutile, viene clearata all'uscita

2018-04-19 15:21 UTC, FIAV1 commented on superpeer/handler/MenuHandler.py
> +				print(f'\n{count}) {LocalData.get_shared_filename(file)}')
,end=''

2018-04-19 15:37 UTC, merged